export class PhoneNumber {
    country: string;
    area: string;
    prefix: string;
    line: string;
  
    // format phone numbers as E.164
    get e164() {
      var cc = [{countryCode:"a", value:"m"}];
      const num = this.country + this.area + this.prefix + this.line
      return `+${num}`
    }  
  }

  export const CountryCodes = [{ countryCode: "DZ" ,value: "213" ,display: "Algeria (+213)" },
    { countryCode: "AD" ,value: "376" ,display: "Andorra (+376)" },
    { countryCode: "AO" ,value: "244" ,display: "Angola (+244)" },
    { countryCode: "AI" ,value: "1264" ,display: "Anguilla (+1264)" },
    { countryCode: "AG" ,value: "1268" ,display: "Antigua &amp; Barbuda (+1268)" },
    { countryCode: "AR" ,value: "54" ,display: "Argentina (+54)" },
    { countryCode: "AM" ,value: "374" ,display: "Armenia (+374)" },
    { countryCode: "AW" ,value: "297" ,display: "Aruba (+297)" },
    { countryCode: "AU" ,value: "61" ,display: "Australia (+61)" },
    { countryCode: "AT" ,value: "43" ,display: "Austria (+43)" },
    { countryCode: "AZ" ,value: "994" ,display: "Azerbaijan (+994)" },
    { countryCode: "BS" ,value: "1242" ,display: "Bahamas (+1242)" },
    { countryCode: "BH" ,value: "973" ,display: "Bahrain (+973)" },
    { countryCode: "BD" ,value: "880" ,display: "Bangladesh (+880)" },
    { countryCode: "BB" ,value: "1246" ,display: "Barbados (+1246)" },
    { countryCode: "BY" ,value: "375" ,display: "Belarus (+375)" },
    { countryCode: "BE" ,value: "32" ,display: "Belgium (+32)" },
    { countryCode: "BZ" ,value: "501" ,display: "Belize (+501)" },
    { countryCode: "BJ" ,value: "229" ,display: "Benin (+229)" },
    { countryCode: "BM" ,value: "1441" ,display: "Bermuda (+1441)" },
    { countryCode: "BT" ,value: "975" ,display: "Bhutan (+975)" },
    { countryCode: "BO" ,value: "591" ,display: "Bolivia (+591)" },
    { countryCode: "BA" ,value: "387" ,display: "Bosnia Herzegovina (+387)" },
    { countryCode: "BW" ,value: "267" ,display: "Botswana (+267)" },
    { countryCode: "BR" ,value: "55" ,display: "Brazil (+55)" },
    { countryCode: "BN" ,value: "673" ,display: "Brunei (+673)" },
    { countryCode: "BG" ,value: "359" ,display: "Bulgaria (+359)" },
    { countryCode: "BF" ,value: "226" ,display: "Burkina Faso (+226)" },
    { countryCode: "BI" ,value: "257" ,display: "Burundi (+257)" },
    { countryCode: "KH" ,value: "855" ,display: "Cambodia (+855)" },
    { countryCode: "CM" ,value: "237" ,display: "Cameroon (+237)" },
    { countryCode: "CA" ,value: "1" ,display: "Canada (+1)" },
    { countryCode: "CV" ,value: "238" ,display: "Cape Verde Islands (+238)" },
    { countryCode: "KY" ,value: "1345" ,display: "Cayman Islands (+1345)" },
    { countryCode: "CF" ,value: "236" ,display: "Central African Republic (+236)" },
    { countryCode: "CL" ,value: "56" ,display: "Chile (+56)" },
    { countryCode: "CN" ,value: "86" ,display: "China (+86)" },
    { countryCode: "CO" ,value: "57" ,display: "Colombia (+57)" },
    { countryCode: "KM" ,value: "269" ,display: "Comoros (+269)" },
    { countryCode: "CG" ,value: "242" ,display: "Congo (+242)" },
    { countryCode: "CK" ,value: "682" ,display: "Cook Islands (+682)" },
    { countryCode: "CR" ,value: "506" ,display: "Costa Rica (+506)" },
    { countryCode: "HR" ,value: "385" ,display: "Croatia (+385)" },
    { countryCode: "CU" ,value: "53" ,display: "Cuba (+53)" },
    { countryCode: "CY" ,value: "90392" ,display: "Cyprus North (+90392)" },
    { countryCode: "CY" ,value: "357" ,display: "Cyprus South (+357)" },
    { countryCode: "CZ" ,value: "42" ,display: "Czech Republic (+42)" },
    { countryCode: "DK" ,value: "45" ,display: "Denmark (+45)" },
    { countryCode: "DJ" ,value: "253" ,display: "Djibouti (+253)" },
    { countryCode: "DM" ,value: "1809" ,display: "Dominica (+1809)" },
    { countryCode: "DO" ,value: "1809" ,display: "Dominican Republic (+1809)" },
    { countryCode: "EC" ,value: "593" ,display: "Ecuador (+593)" },
    { countryCode: "EG" ,value: "20" ,display: "Egypt (+20)" },
    { countryCode: "SV" ,value: "503" ,display: "El Salvador (+503)" },
    { countryCode: "GQ" ,value: "240" ,display: "Equatorial Guinea (+240)" },
    { countryCode: "ER" ,value: "291" ,display: "Eritrea (+291)" },
    { countryCode: "EE" ,value: "372" ,display: "Estonia (+372)" },
    { countryCode: "ET" ,value: "251" ,display: "Ethiopia (+251)" },
    { countryCode: "FK" ,value: "500" ,display: "Falkland Islands (+500)" },
    { countryCode: "FO" ,value: "298" ,display: "Faroe Islands (+298)" },
    { countryCode: "FJ" ,value: "679" ,display: "Fiji (+679)" },
    { countryCode: "FI" ,value: "358" ,display: "Finland (+358)" },
    { countryCode: "FR" ,value: "33" ,display: "France (+33)" },
    { countryCode: "GF" ,value: "594" ,display: "French Guiana (+594)" },
    { countryCode: "PF" ,value: "689" ,display: "French Polynesia (+689)" },
    { countryCode: "GA" ,value: "241" ,display: "Gabon (+241)" },
    { countryCode: "GM" ,value: "220" ,display: "Gambia (+220)" },
    { countryCode: "GE" ,value: "7880" ,display: "Georgia (+7880)" },
    { countryCode: "DE" ,value: "49" ,display: "Germany (+49)" },
    { countryCode: "GH" ,value: "233" ,display: "Ghana (+233)" },
    { countryCode: "GI" ,value: "350" ,display: "Gibraltar (+350)" },
    { countryCode: "GR" ,value: "30" ,display: "Greece (+30)" },
    { countryCode: "GL" ,value: "299" ,display: "Greenland (+299)" },
    { countryCode: "GD" ,value: "1473" ,display: "Grenada (+1473)" },
    { countryCode: "GP" ,value: "590" ,display: "Guadeloupe (+590)" },
    { countryCode: "GU" ,value: "671" ,display: "Guam (+671)" },
    { countryCode: "GT" ,value: "502" ,display: "Guatemala (+502)" },
    { countryCode: "GN" ,value: "224" ,display: "Guinea (+224)" },
    { countryCode: "GW" ,value: "245" ,display: "Guinea - Bissau (+245)" },
    { countryCode: "GY" ,value: "592" ,display: "Guyana (+592)" },
    { countryCode: "HT" ,value: "509" ,display: "Haiti (+509)" },
    { countryCode: "HN" ,value: "504" ,display: "Honduras (+504)" },
    { countryCode: "HK" ,value: "852" ,display: "Hong Kong (+852)" },
    { countryCode: "HU" ,value: "36" ,display: "Hungary (+36)" },
    { countryCode: "IS" ,value: "354" ,display: "Iceland (+354)" },
    { countryCode: "IN" ,value: "91" ,display: "India (+91)" },
    { countryCode: "ID" ,value: "62" ,display: "Indonesia (+62)" },
    { countryCode: "IR" ,value: "98" ,display: "Iran (+98)" },
    { countryCode: "IQ" ,value: "964" ,display: "Iraq (+964)" },
    { countryCode: "IE" ,value: "353" ,display: "Ireland (+353)" },
    { countryCode: "IL" ,value: "972" ,display: "Israel (+972)" },
    { countryCode: "IT" ,value: "39" ,display: "Italy (+39)" },
    { countryCode: "JM" ,value: "1876" ,display: "Jamaica (+1876)" },
    { countryCode: "JP" ,value: "81" ,display: "Japan (+81)" },
    { countryCode: "JO" ,value: "962" ,display: "Jordan (+962)" },
    { countryCode: "KZ" ,value: "7" ,display: "Kazakhstan (+7)" },
    { countryCode: "KE" ,value: "254" ,display: "Kenya (+254)" },
    { countryCode: "KI" ,value: "686" ,display: "Kiribati (+686)" },
    { countryCode: "KP" ,value: "850" ,display: "Korea North (+850)" },
    { countryCode: "KR" ,value: "82" ,display: "Korea South (+82)" },
    { countryCode: "KW" ,value: "965" ,display: "Kuwait (+965)" },
    { countryCode: "KG" ,value: "996" ,display: "Kyrgyzstan (+996)" },
    { countryCode: "LA" ,value: "856" ,display: "Laos (+856)" },
    { countryCode: "LV" ,value: "371" ,display: "Latvia (+371)" },
    { countryCode: "LB" ,value: "961" ,display: "Lebanon (+961)" },
    { countryCode: "LS" ,value: "266" ,display: "Lesotho (+266)" },
    { countryCode: "LR" ,value: "231" ,display: "Liberia (+231)" },
    { countryCode: "LY" ,value: "218" ,display: "Libya (+218)" },
    { countryCode: "LI" ,value: "417" ,display: "Liechtenstein (+417)" },
    { countryCode: "LT" ,value: "370" ,display: "Lithuania (+370)" },
    { countryCode: "LU" ,value: "352" ,display: "Luxembourg (+352)" },
    { countryCode: "MO" ,value: "853" ,display: "Macao (+853)" },
    { countryCode: "MK" ,value: "389" ,display: "Macedonia (+389)" },
    { countryCode: "MG" ,value: "261" ,display: "Madagascar (+261)" },
    { countryCode: "MW" ,value: "265" ,display: "Malawi (+265)" },
    { countryCode: "MY" ,value: "60" ,display: "Malaysia (+60)" },
    { countryCode: "MV" ,value: "960" ,display: "Maldives (+960)" },
    { countryCode: "ML" ,value: "223" ,display: "Mali (+223)" },
    { countryCode: "MT" ,value: "356" ,display: "Malta (+356)" },
    { countryCode: "MH" ,value: "692" ,display: "Marshall Islands (+692)" },
    { countryCode: "MQ" ,value: "596" ,display: "Martinique (+596)" },
    { countryCode: "MR" ,value: "222" ,display: "Mauritania (+222)" },
    { countryCode: "YT" ,value: "269" ,display: "Mayotte (+269)" },
    { countryCode: "MX" ,value: "52" ,display: "Mexico (+52)" },
    { countryCode: "FM" ,value: "691" ,display: "Micronesia (+691)" },
    { countryCode: "MD" ,value: "373" ,display: "Moldova (+373)" },
    { countryCode: "MC" ,value: "377" ,display: "Monaco (+377)" },
    { countryCode: "MN" ,value: "976" ,display: "Mongolia (+976)" },
    { countryCode: "MS" ,value: "1664" ,display: "Montserrat (+1664)" },
    { countryCode: "MA" ,value: "212" ,display: "Morocco (+212)" },
    { countryCode: "MZ" ,value: "258" ,display: "Mozambique (+258)" },
    { countryCode: "MN" ,value: "95" ,display: "Myanmar (+95)" },
    { countryCode: "NA" ,value: "264" ,display: "Namibia (+264)" },
    { countryCode: "NR" ,value: "674" ,display: "Nauru (+674)" },
    { countryCode: "NP" ,value: "977" ,display: "Nepal (+977)" },
    { countryCode: "NL" ,value: "31" ,display: "Netherlands (+31)" },
    { countryCode: "NC" ,value: "687" ,display: "New Caledonia (+687)" },
    { countryCode: "NZ" ,value: "64" ,display: "New Zealand (+64)" },
    { countryCode: "NI" ,value: "505" ,display: "Nicaragua (+505)" },
    { countryCode: "NE" ,value: "227" ,display: "Niger (+227)" },
    { countryCode: "NG" ,value: "234" ,display: "Nigeria (+234)" },
    { countryCode: "NU" ,value: "683" ,display: "Niue (+683)" },
    { countryCode: "NF" ,value: "672" ,display: "Norfolk Islands (+672)" },
    { countryCode: "NP" ,value: "670" ,display: "Northern Marianas (+670)" },
    { countryCode: "NO" ,value: "47" ,display: "Norway (+47)" },
    { countryCode: "OM" ,value: "968" ,display: "Oman (+968)" },
    { countryCode: "PW" ,value: "680" ,display: "Palau (+680)" },
    { countryCode: "PA" ,value: "507" ,display: "Panama (+507)" },
    { countryCode: "PG" ,value: "675" ,display: "Papua New Guinea (+675)" },
    { countryCode: "PY" ,value: "595" ,display: "Paraguay (+595)" },
    { countryCode: "PE" ,value: "51" ,display: "Peru (+51)" },
    { countryCode: "PH" ,value: "63" ,display: "Philippines (+63)" },
    { countryCode: "PL" ,value: "48" ,display: "Poland (+48)" },
    { countryCode: "PT" ,value: "351" ,display: "Portugal (+351)" },
    { countryCode: "PR" ,value: "1787" ,display: "Puerto Rico (+1787)" },
    { countryCode: "QA" ,value: "974" ,display: "Qatar (+974)" },
    { countryCode: "RE" ,value: "262" ,display: "Reunion (+262)" },
    { countryCode: "RO" ,value: "40" ,display: "Romania (+40)" },
    { countryCode: "RU" ,value: "7" ,display: "Russia (+7)" },
    { countryCode: "RW" ,value: "250" ,display: "Rwanda (+250)" },
    { countryCode: "SM" ,value: "378" ,display: "San Marino (+378)" },
    { countryCode: "ST" ,value: "239" ,display: "Sao Tome &amp; Principe (+239)" },
    { countryCode: "SA" ,value: "966" ,display: "Saudi Arabia (+966)" },
    { countryCode: "SN" ,value: "221" ,display: "Senegal (+221)" },
    { countryCode: "CS" ,value: "381" ,display: "Serbia (+381)" },
    { countryCode: "SC" ,value: "248" ,display: "Seychelles (+248)" },
    { countryCode: "SL" ,value: "232" ,display: "Sierra Leone (+232)" },
    { countryCode: "SG" ,value: "65" ,display: "Singapore (+65)" },
    { countryCode: "SK" ,value: "421" ,display: "Slovak Republic (+421)" },
    { countryCode: "SI" ,value: "386" ,display: "Slovenia (+386)" },
    { countryCode: "SB" ,value: "677" ,display: "Solomon Islands (+677)" },
    { countryCode: "SO" ,value: "252" ,display: "Somalia (+252)" },
    { countryCode: "ZA" ,value: "27" ,display: "South Africa (+27)" },
    { countryCode: "ES" ,value: "34" ,display: "Spain (+34)" },
    { countryCode: "LK" ,value: "94" ,display: "Sri Lanka (+94)" },
    { countryCode: "SH" ,value: "290" ,display: "St. Helena (+290)" },
    { countryCode: "KN" ,value: "1869" ,display: "St. Kitts (+1869)" },
    { countryCode: "SC" ,value: "1758" ,display: "St. Lucia (+1758)" },
    { countryCode: "SD" ,value: "249" ,display: "Sudan (+249)" },
    { countryCode: "SR" ,value: "597" ,display: "Suriname (+597)" },
    { countryCode: "SZ" ,value: "268" ,display: "Swaziland (+268)" },
    { countryCode: "SE" ,value: "46" ,display: "Sweden (+46)" },
    { countryCode: "CH" ,value: "41" ,display: "Switzerland (+41)" },
    { countryCode: "SI" ,value: "963" ,display: "Syria (+963)" },
    { countryCode: "TW" ,value: "886" ,display: "Taiwan (+886)" },
    { countryCode: "TJ" ,value: "7" ,display: "Tajikstan (+7)" },
    { countryCode: "TH" ,value: "66" ,display: "Thailand (+66)" },
    { countryCode: "TG" ,value: "228" ,display: "Togo (+228)" },
    { countryCode: "TO" ,value: "676" ,display: "Tonga (+676)" },
    { countryCode: "TT" ,value: "1868" ,display: "Trinidad &amp; Tobago (+1868)" },
    { countryCode: "TN" ,value: "216" ,display: "Tunisia (+216)" },
    { countryCode: "TR" ,value: "90" ,display: "Turkey (+90)" },
    { countryCode: "TM" ,value: "7" ,display: "Turkmenistan (+7)" },
    { countryCode: "TM" ,value: "993" ,display: "Turkmenistan (+993)" },
    { countryCode: "TC" ,value: "1649" ,display: "Turks &amp; Caicos Islands (+1649)" },
    { countryCode: "TV" ,value: "688" ,display: "Tuvalu (+688)" },
    { countryCode: "UG" ,value: "256" ,display: "Uganda (+256)" },
    { countryCode: "GB" ,value: "44" ,display: "UK (+44)" },
    { countryCode: "UA" ,value: "380" ,display: "Ukraine (+380)" },
    { countryCode: "AE" ,value: "971" ,display: "United Arab Emirates (+971)" },
    { countryCode: "US" ,value: "1" ,display: "United States of America (+1)" },
    { countryCode: "UY" ,value: "598" ,display: "Uruguay (+598)" },
    { countryCode: "UZ" ,value: "7" ,display: "Uzbekistan (+7)" },
    { countryCode: "VU" ,value: "678" ,display: "Vanuatu (+678)" },
    { countryCode: "VA" ,value: "379" ,display: "Vatican City (+379)" },
    { countryCode: "VE" ,value: "58" ,display: "Venezuela (+58)" },
    { countryCode: "VN" ,value: "84" ,display: "Vietnam (+84)" },
    { countryCode: "VG" ,value: "84" ,display: "Virgin Islands - British (+1284)" },
    { countryCode: "VI" ,value: "84" ,display: "Virgin Islands - US (+1340)" },
    { countryCode: "WF" ,value: "681" ,display: "Wallis &amp; Futuna (+681)" },
    { countryCode: "YE" ,value: "969" ,display: "Yemen (North)(+969)" },
    { countryCode: "YE" ,value: "967" ,display: "Yemen (South)(+967)" },
    { countryCode: "ZM" ,value: "260" ,display: "Zambia (+260)" },
    { countryCode: "ZW" ,value: "263" ,display: "Zimbabwe (+263)" }
    ];
